<?php

require_once 'connect.php';

$module_id = $_POST['module_id'];
$query = "SELECT * FROM module WHERE id='$module_id'";
$result = mysqli_query($conn, $query);
$modulecheck = mysqli_num_rows($result);
if ($modulecheck > 0) {
    $row = mysqli_fetch_assoc($result);
    echo (json_encode(array("statusCode" => 200, "message" => "Module found!",
        "module_id" => $row['id'],
        "module_code" => $row['kode'],
        "module_label" => $row['label'],
        "part_number" => $row['part_number'],
        "serial_number" => $row['serial_number'],
        "modul" => $row['modul'],
        "fasilitas" => $row['fasilitas'],
        "peralatan" => $row['peralatan'],
        "merk" => $row['merk'],
        "tipe" => $row['tipe'],
        "level" => $row['level'],
        "induk_id" => $row['induk_id'],
        "induk_sn" => $row['induk_sn'],
        "asal_pengadaan" => $row['asal_pengadaan'],
        "status_asal" => $row['status_asal'],
        "tahun_pengadaan" => $row['tahun_pengadaan'],
        "harga_perolehan" => $row['harga_perolehan'],
        "kondisi_asal" => $row['kondisi_asal'],
        "catatan_kondisi" => $row['catatan_kondisi'],
        "lokasi_asal" => $row['lokasi_asal'],
        "konfirmasi_asal" => $row['konfirmasi_asal'],
        "tanggal_kirim" => $row['tanggal_kirim'],
        "tanggal_masuk" => $row['tanggal_masuk'],
        "konfirmasi_barang" => $row['konfirmasi_barang'],
        "kode_material" => $row['kode_material'],
        "nomor_basto" => $row['nomor_basto'],
        "urutan_basto" => $row['urutan_basto'],
        "nomor_po" => $row['no_purchased_order'],
        "nomor_good_issued" => $row['no_good_issued'],
        "nomor_issued_good_out" => $row['no_good_issued_out'],
        "nomor_good_receipt_out" => $row['no_good_receipt_out'],
        "berita_acara" => $row['berita_acara'],
        "berita_acara_out" => $row['berita_acara_out'],
        "file_berita_acara" => $row['file_berita_acara'],
        "file_ba_out" => $row['file_ba_out'],
        "ba_pejabat_kirim" => $row['ba_pejabat_kirim'],
        "ba_nama_kirim" => $row['ba_nama_kirim'],
        "ba_pejabat_terima" => $row['ba_pejabat_terima'],
        "ba_nama_terima" => $row['ba_nama_terima'],
        "sap" => $row['sap'], 
        "alims" => $row['alims'],
        "catatan_gudang" => $row['catatan_gudang'],
        "wo_kode" => $row['wo_kode'],
        "wo_pejabat" => $row['wo_pejabat'],
        "wo_expert" => $row['wo_expert'],
        "wo_teknisi" => $row['wo_teknisi'],
        "wo_tanggal" => $row['wo_tanggal'],
        "tanggal_repair" => $row['tanggal_repair'],
        "tanggal_selesai" => $row['tanggal_selesai'],
        "catatan_modul" => $row['catatan_modul'],
        "komponen" => $row['komponen'],
        "tool" => $row['tool'],
        "material" => $row['material'],
        "biaya" => $row['biaya'],
        "prioritas" => $row['prioritas'],
        "qc_teknisi" => $row['qc_teknisi'],
        "qc_mulai" => $row['qc_mulai'],
        "qc_selesai" => $row['qc_selesai'],
        "qc_status" => $row['qc_status'],
        "tanggal_laporan" => $row['tanggal_laporan'],
        "tanggal_keluar" => $row['tanggal_keluar'],
        "tanggal_terima" => $row['tanggal_terima'],
        "status_modul" => $row['status_modul'],
        "proses" => $row['proses'],
        "status_repair" => $row['status_repair'],
        "gudang" => $row['gudang'],
        "status_pasang" => $row['posisi'],
        "keterangan" => $row['keterangan'],
        "created_at" => $row['created_at'],
        "updated_at" => $row['updated_at'])));
} else {
    echo (json_encode(array("statusCode" => 404, "message" => "Module does not exist!")));
}

